author = "EntropyGraph"
copyright = ""
keywords = ""
description = "Privacy ∙ Integrity ∙ Availability ∙ Consensus"
profilePicture = "images/vertical-logo-inverse.svg"
favicon = "favicons/"
customCss =  ["css/custom.css"]
customJs = []
mainSections = ["services"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

displayMode = "dark"
disableThemeSwitcher = true

# Read More links for truncated summaries
readMore = false
# postSectionName = "blog"

[simpleAnalytics]
enable = false

## Math settings
[math]
enable = false
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/entropygraph"

[[socialIcons]]
icon = "fab fa-telegram-plane"
title = "Telegram"
url = "https://t.me/EntropyGraph"

[[socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:tyler@entropyaccumulating.com"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/entropygraph"
