
author = "EntropyGraph"
copyright = ""
description = "Privacy ∙ Integrity ∙ Availability ∙ Consensus"
profilePicture = "images/vertical-logo-inverse.svg"
keywords = ""
favicon = "favicons/favicon.ico"
customCss =  ["css/custom.css"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[simpleAnalytics]
enable = false

## Math settings
[math]
enable = true
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://de.linkedin.com/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[socialIcons]]
icon = "fab fa-telegram-plane"
title = "Telegram"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:mail@example.com"
