baseURL = "https://entropygra.ph"
languageCode = "en-us"
theme = "pulp"
disableKinds = ["tag", "section", "taxonomy", "taxonomyTerm", "RSS", "404", "sitemap"]


[author]
name = "EntropyGraph"
email = "tyler@entropyaccumulating.com"
homepage = "https://entropygra.ph"

[params]
author = "EntropyGraph"
avatar = "avatar.png"
favicon = "favicon.ico"
description = """Privacy ∙ Integrity ∙ Availability ∙ Consensus"""

[[menu.main]]
identifier = "twitter"
pre = "<i class='fab fa-twitter fa-lg'></i>"
url = "https://twitter.com/entropygraph"
weight = 10

[[menu.main]]
identifier = "github"
#name = "GitHub"
pre = "<i class='fab fa-github fa-lg'></i>"
url = "https://github.com/entropygraph"
weight = 20

[[menu.main]]
identifier = "telegram"
# name = "Email"
pre = "<i class='fab fa-telegram-plane fa-lg'></i>"
url = "https://t.me/tcrypt25519"
weight = 40

[[menu.main]]
identifier = "email"
# name = "Email"
pre = "<i class='fa fa-envelope fa-lg'></i>"
url = "mailto:tyler@entropyaccumulating.com"
weight = 100
